import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core'
import { sql } from 'drizzle-orm'

export const collections = sqliteTable('collections', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  type: text('type').notNull(),
  query: text('query').notNull(),
  limitPerItem: integer('limit_per_item').notNull().default(30),
  status: text('status').notNull().default('pending'),
  totalCollected: integer('total_collected').notNull().default(0),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
})

export const posts = sqliteTable('posts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  collectionId: integer('collection_id').notNull().references(() => collections.id),
  shortcode: text('shortcode').notNull().unique(),
  url: text('url'),
  caption: text('caption'),
  ownerUsername: text('owner_username'),
  ownerFullname: text('owner_fullname'),
  likes: integer('likes').default(0),
  comments: integer('comments').default(0),
  postTimestamp: text('post_timestamp'),
  location: text('location'),
  hashtags: text('hashtags').default('[]'),
  postType: text('post_type'),
  displayUrl: text('display_url'),
  videoViewCount: integer('video_view_count').default(0),
  mentions: text('mentions').default('[]'),
  isVideo: integer('is_video').default(0),
  searchTag: text('search_tag'),
  ownerId: text('owner_id').default(''),
  dimensionsWidth: integer('dimensions_width').default(0),
  dimensionsHeight: integer('dimensions_height').default(0),
  images: text('images').default('[]'),
  firstComment: text('first_comment').default(''),
  latestComments: text('latest_comments').default('[]'),
  musicInfo: text('music_info').default(''),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_posts_collection').on(table.collectionId),
  index('idx_posts_username').on(table.ownerUsername),
  index('idx_posts_likes').on(table.likes),
])

export const influencers = sqliteTable('influencers', {
  username: text('username').primaryKey(),
  fullname: text('fullname'),
  profileUrl: text('profile_url'),
  postCount: integer('post_count').default(0),
  avgLikes: real('avg_likes').default(0),
  avgComments: real('avg_comments').default(0),
  avgEngagement: real('avg_engagement').default(0),
  hashtags: text('hashtags').default('[]'),
  status: text('status').notNull().default('미확인'),
  memo: text('memo').default(''),
  bio: text('bio').default(''),
  followers: integer('followers').default(0),
  following: integer('following').default(0),
  isBusiness: integer('is_business').default(0),
  totalPosts: integer('total_posts').default(0),
  isVerified: integer('is_verified').default(0),
  externalUrl: text('external_url').default(''),
  category: text('category').default(''),
  profilePicUrl: text('profile_pic_url').default(''),
  engagementRate: real('engagement_rate').default(0),
  fitScore: real('fit_score').default(0),
  commentLikeRatio: real('comment_like_ratio').default(0),
  followerFollowingRatio: real('follower_following_ratio').default(0),
  postingFrequency: real('posting_frequency').default(0),
  lastPostDate: text('last_post_date').default(''),
  contentRelevance: real('content_relevance').default(0),
  detectedLanguage: text('detected_language').default(''),
  commentLangDistribution: text('comment_lang_distribution').default('{}'),
  commentQualityScore: real('comment_quality_score').default(0),
  deepAnalyzedAt: text('deep_analyzed_at').default(''),
  reelCount: integer('reel_count').default(0),
  avgReelViews: real('avg_reel_views').default(0),
  avgReelPlays: real('avg_reel_plays').default(0),
  lastUpdated: text('last_updated').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_influencers_engagement').on(table.avgEngagement),
])

export const reels = sqliteTable('reels', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  username: text('username').notNull(),
  reelUrl: text('reel_url').notNull().unique(),
  shortcode: text('shortcode'),
  caption: text('caption'),
  likes: integer('likes').default(0),
  commentsCount: integer('comments_count').default(0),
  views: integer('views').default(0),
  plays: integer('plays').default(0),
  duration: real('duration').default(0),
  postTimestamp: text('post_timestamp'),
  videoUrl: text('video_url').default(''),
  displayUrl: text('display_url').default(''),
  audioTitle: text('audio_title').default(''),
  hashtags: text('hashtags').default('[]'),
  ownerFullname: text('owner_fullname').default(''),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_reels_username').on(table.username),
])

export const reelComments = sqliteTable('reel_comments', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  reelId: integer('reel_id').notNull().references(() => reels.id),
  commentText: text('comment_text'),
  commenterUsername: text('commenter_username'),
  likes: integer('likes').default(0),
  isReply: integer('is_reply').default(0),
  detectedLanguage: text('detected_language').default(''),
  commentTimestamp: text('comment_timestamp'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_reel_comments_reel').on(table.reelId),
  index('idx_reel_comments_lang').on(table.detectedLanguage),
])

export const apifyKeys = sqliteTable('apify_keys', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  token: text('token').notNull().unique(),
  label: text('label').notNull(),
  monthlyLimit: real('monthly_limit').default(5.0),
  currentUsage: real('current_usage').default(0),
  remaining: real('remaining').default(5.0),
  isActive: integer('is_active').default(1),
  isSelected: integer('is_selected').default(0),
  lastChecked: text('last_checked').default(''),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
})
