-- Create a table for storing consultation forms
create table consultations (
  id bigint generated by default as identity primary key,
  hospital_name text not null,
  contact_name text not null,
  phone text not null,
  email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table consultations enable row level security;

-- Policy: Allow public to insert data (for the contact form)
create policy "Allow public inserts"
  on consultations for insert
  with check (true);

-- Policy: Allow only authenticated users (admins) to view data
create policy "Allow individual read access"
  on consultations for select
  using (auth.role() = 'authenticated');
